export const hobby = [
  "archery",
  "astronomy (stargazing)",
  "baking",
  "basketball",
  "bird watching",
  "blogging",
  "board games",
  "calligraphy",
  "camping",
  "candle making",
  "chess",
  "collecting",
  "cooking",
  "cycling",
  "dancing",
  "diy projects",
  "art & craft",
  "drawing",
  "fishing",
  "fitness training",
  "gardening",
  "hiking",
  "home brewing",
  "interior decorating",
  "jewelry making",
  "journaling",
  "kite flying",
  "knitting or crocheting",
  "learning instruments",
  "leather crafting",
  "martial arts",
  "model building",
  "mountain biking",
  "origami",
  "painting",
  "papercraft",
  "pet training",
  "photography",
  "play music",
  "pottery",
  "puzzles",
  "reading books",
  "rock climbing",
  "running",
  "scrapbooking",
  "sewing",
  "singing",
  "skateboarding",
  "sketching",
  "surfing",
  "swimming",
  "table tennis",
  "traveling",
  "video gaming",
  "video editing",
  "volunteering",
  "walking",
  "watching movies",
  "weightlifting",
  "woodworking",
  "writing",
  "yoga",
  "cricket",
  "football",
  "zumba",
  "others"
]
